name: Mi Primer Action

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Paso 1 - Descargar código
        uses: actions/checkout@v4
        
      - name: Paso 2 - Mensaje de éxito
        run: echo "🎉 ¡FUNCIONA! GitHub Actions está vivo"
        
      - name: Paso 3 - Mostrar archivos
        run: ls -la